image: docker:19.03.8
pipelines:
  branches:
    master:
    - step:
        size: 2x
        name: Deploy to Prod
        script:
        - apk update && apk add make && apk add openssh
        - docker login $REGISTRY --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        - make build-image TAG=$BITBUCKET_BUILD_NUMBER REGISTRY=$REGISTRY
        - make push-image  TAG=$BITBUCKET_BUILD_NUMBER REGISTRY=$REGISTRY
        - source .build_info
        - ssh delever@$DELEVER_PROD_HOST 'docker service update --with-registry-auth
          --image '$REGISTRY'/'$APP':'$BITBUCKET_BUILD_NUMBER' '$APP''
        services:
        - docker
#    - step:
#        image: maven:3.3.9
#        name: Run tests
#        script:
#        - git clone git@bitbucket.org:alien_soft/delever_api_tests.git
#        - cd delever_api_tests
#        - mvn clean test -DfileName=branchService.xml -Dserver=https://api.delever.uz/v1
    staging:
    - step:
        name: Deploy to Staging
        size: 2x
        script:
        - apk update && apk add make && apk add openssh
        - docker login $REGISTRY --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        - make build-image TAG=$BITBUCKET_BUILD_NUMBER ENV_TAG=test REGISTRY=$REGISTRY
        - make push-image  TAG=$BITBUCKET_BUILD_NUMBER ENV_TAG=test REGISTRY=$REGISTRY
        - source .build_info
        - ssh delever@$DELEVER_TEST_HOST 'docker service update --with-registry-auth
          --image '$REGISTRY'/'$APP':'$BITBUCKET_BUILD_NUMBER' '$APP''
        services:
        - docker

definitions:
  services:
    docker:
      memory: 7168


