FROM node:14.17.5-alpine as builder
RUN apk update && apk add yarn

RUN mkdir app
WORKDIR app

COPY package*.json ./
RUN yarn install


COPY . ./
RUN apk add git
RUN rm -rf .env && mv .env.development .env && yarn build

FROM nginx:alpine
COPY --from=builder /app/dist /dist
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]


